import Link from"next/link";import{products}from"@/lib/data";import{ProductGrid}from"@/components/ProductCard";import Img from"@/components/Img";
const cats=[["Women","/women","grad:#E8B4B8,#F7E6E3"],["Kids","/kids","grad:#D9C7A8,#F1E9DA"],["Mother & Daughter","/matching","grad:#A9B8A0,#E3E9DE"]];
const why=[["Cash on Delivery","Pay when your order arrives."],["Nationwide Delivery","Dhaka and all 64 districts."],["Easy Exchange","Wrong size? We'll swap it."],["Quality Checked","Every piece inspected before dispatch."]];
export default function Home(){return<>
<section className="bg-blush/50"><div className="wrap grid items-center gap-8 py-12 md:grid-cols-2 md:py-20"><div><h1 className="font-serif text-5xl leading-[1.05] sm:text-6xl lg:text-7xl">Style for Every Little Moment</h1><p className="mt-5 max-w-md text-lg text-ink/70">Discover effortless fashion for women and little ones.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/women" className="btn">SHOP WOMEN</Link><Link href="/kids" className="btn-o">SHOP KIDS</Link></div></div>
<Img src="grad:#E8B4B8,#E7DDCD" alt="MIORA hero (replace with campaign image)" className="aspect-[4/5] rounded-[2rem]"/></div></section>
<section className="wrap mt-16"><div className="grid gap-4 md:grid-cols-3">{cats.map(([t,h,g])=><Link key={h} href={h} className="group relative block aspect-[4/5] overflow-hidden rounded-3xl"><Img src={g} alt={t} className="absolute inset-0 transition duration-700 group-hover:scale-105"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-6"><h2 className="font-serif text-3xl">{t}</h2><span className="rounded-full bg-white px-4 py-2 text-sm">Shop now</span></div></Link>)}</div></section>
<section className="wrap mt-20"><div className="mb-6 flex items-end justify-between"><h2 className="font-serif text-4xl">New Arrivals</h2><Link href="/new-arrivals" className="text-sm underline">View all</Link></div><ProductGrid items={products.filter(p=>p.newArrival).slice(0,8)}/></section>
<section className="mt-20 bg-ink text-cream"><div className="wrap grid items-center gap-8 py-16 md:grid-cols-2"><Img src="grad:#E8B4B8,#D9C7A8" alt="Matching collection" className="aspect-[4/3] rounded-3xl"/><div><h2 className="font-serif text-4xl sm:text-5xl">Made for Her. Made for Little Her.</h2><p className="mt-4 text-cream/70">Matching styles for beautiful moments together.</p><Link href="/matching" className="mt-8 inline-flex rounded-full bg-cream px-7 py-3 text-sm font-medium text-ink">SHOP MATCHING</Link></div></div></section>
<section className="wrap mt-20"><h2 className="mb-6 font-serif text-4xl">Best Sellers</h2><ProductGrid items={products.filter(p=>p.bestSeller).slice(0,8)}/></section>
<section className="wrap mt-20"><h2 className="mb-6 font-serif text-4xl">Why choose MIORA</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{why.map(([t,d])=><div key={t} className="rounded-2xl bg-white p-6"><h3 className="font-medium">{t}</h3><p className="mt-1 text-sm text-ink/60">{d}</p></div>)}</div></section>
<section className="wrap mt-20"><h2 className="font-serif text-4xl">Customer reviews</h2><p className="mt-2 text-sm text-ink/60">TODO: connect a real review source. Nothing below is a real review.</p><div className="mt-6 grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="rounded-2xl border border-dashed border-ink/25 p-6 text-sm text-ink/50">Review placeholder {i}<br/>★★★★★ (rating slot)</div>)}</div></section>
<section className="wrap mt-20"><h2 className="font-serif text-4xl">Follow the MIORA Story</h2><div className="mt-6 grid grid-cols-3 gap-2 md:grid-cols-6">{["#E8B4B8","#D9C7A8","#A9B8A0","#F2D8D5","#E7DDCD","#C9A9A6"].map(c=><div key={c} className="aspect-square rounded-xl" style={{background:c}} aria-label="Instagram placeholder"/>)}</div></section>
<section className="wrap mt-20"><div className="rounded-3xl bg-sand/60 p-8 text-center sm:p-14"><h2 className="font-serif text-4xl">Be the First to Know</h2><p className="mx-auto mt-3 max-w-md text-ink/70">Get updates about new collections, exclusive offers and special launches.</p><form className="mx-auto mt-6 flex max-w-md flex-col gap-3 sm:flex-row"><input type="email" required placeholder="Enter your email" className="inp"/><button className="btn">SUBSCRIBE</button></form></div></section></>}
