"use client";
import{useState}from"react";import Link from"next/link";import{useRouter}from"next/navigation";
import{Product,fmt,pct}from"@/lib/data";import{DELIVERY}from"@/lib/config";import{useCart}from"@/lib/cart";import Img from"./Img";import SizeGuide from"./SizeGuide";
export default function ProductInfo({p}:{p:Product}){
const{add}=useCart(),r=useRouter(),[img,setImg]=useState(0),[color,setColor]=useState(p.colors[0].name),[size,setSize]=useState(""),[qty,setQty]=useState(1),[tab,setTab]=useState("Description"),[err,setErr]=useState(""),[guide,setGuide]=useState(false);
const go=(buy:boolean)=>{if(!size){setErr("Please select a size.");return}add({id:p.id,slug:p.slug,name:p.name,price:p.price,size,color,qty,img:p.images[0]});if(buy)r.push("/checkout")};
const tabs:Record<string,string>={Description:p.description,"Size & Fit":"Size chart placeholder. Add real measurements here.",Delivery:`Inside Dhaka ${DELIVERY.labels.dhaka} (${DELIVERY.etaDays.dhaka}). Outside Dhaka ${DELIVERY.labels.outside} (${DELIVERY.etaDays.outside}).`,"Exchange Policy":"Exchange policy placeholder. Add your real terms here."};
return<div className="wrap grid gap-10 py-10 md:grid-cols-2">
<div><Img src={p.images[img]} alt={p.name} className="aspect-[3/4] rounded-3xl"/><div className="mt-3 flex gap-3">{p.images.map((s,i)=><button key={i} onClick={()=>setImg(i)} aria-label={`Image ${i+1}`} className={`overflow-hidden rounded-xl border-2 ${i===img?"border-ink":"border-transparent"}`}><Img src={s} alt="" className="h-20 w-16"/></button>)}</div></div>
<div><h1 className="font-serif text-4xl">{p.name}</h1><p className="mt-1 text-sm text-ink/50">Rating: no reviews yet</p>
<p className="mt-4 flex items-center gap-3 text-2xl">{fmt(p.price)}{p.compareAtPrice&&<><span className="text-base text-ink/45 line-through">{fmt(p.compareAtPrice)}</span><span className="rounded-full bg-blush px-3 py-1 text-xs">-{pct(p)}%</span></>}</p>
<p className="mt-6 text-sm font-medium">Color: {color}</p><div className="mt-2 flex gap-2">{p.colors.map(c=><button key={c.name} onClick={()=>setColor(c.name)} aria-label={c.name} className={`h-9 w-9 rounded-full border-2 ${color===c.name?"border-ink":"border-ink/15"}`} style={{background:c.hex}}/>)}</div>
<p className="mt-6 flex justify-between text-sm font-medium">Size <button type="button" onClick={()=>setGuide(true)} className="font-normal underline">Size guide</button></p><div className="mt-2 flex flex-wrap gap-2">{p.sizes.map(s=><button key={s} onClick={()=>{setSize(s);setErr("")}} className={`rounded-full border px-5 py-2 text-sm ${size===s?"border-ink bg-ink text-cream":"border-ink/20"}`}>{s}</button>)}</div>
{err&&<p role="alert" className="mt-2 text-sm text-red-700">{err}</p>}
<div className="mt-6 flex items-center gap-4"><div className="flex items-center gap-4 rounded-full border border-ink/20 px-4 py-2"><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button>{qty}<button onClick={()=>setQty(Math.min(p.stock,qty+1))}>+</button></div><button aria-label="Wishlist" className="grid h-11 w-11 place-items-center rounded-full border border-ink/20">♡</button></div>
<div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={()=>go(false)} className="btn-o">Add to cart</button><button onClick={()=>go(true)} className="btn">Buy now</button></div>
<div className="mt-10 border-t border-ink/10 pt-4"><div className="flex gap-5 overflow-x-auto text-sm">{Object.keys(tabs).map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap pb-2 ${tab===t?"border-b-2 border-ink font-medium":"text-ink/50"}`}>{t}</button>)}</div><p className="mt-3 text-sm leading-relaxed text-ink/70">{tabs[tab]}</p></div></div>{guide&&<SizeGuide onClose={()=>setGuide(false)}/>}</div>}
