"use client";
import{useState}from"react";import{useRouter}from"next/navigation";import{useCart}from"@/lib/cart";import{fmt}from"@/lib/data";import{DELIVERY}from"@/lib/config";
export default function Checkout(){const{lines,subtotal,delivery,clear}=useCart(),r=useRouter(),[zone,setZone]=useState<"dhaka"|"outside">("dhaka"),[pay,setPay]=useState("Cash on Delivery");
const total=subtotal+delivery(zone);
const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;
// TODO: POST to your orders API here; use the returned order number.
const order={no:"MIO-"+Date.now().toString().slice(-7),name:f.name,total,zone,pay};sessionStorage.setItem("miora-order",JSON.stringify(order));clear();r.push("/order-confirmation")};
return<form onSubmit={submit} className="wrap grid gap-10 py-10 lg:grid-cols-[1fr_380px]"><div className="space-y-4"><h1 className="font-serif text-4xl">Checkout</h1>
<input name="name" required placeholder="Customer name" className="inp"/><input name="mobile" required pattern="01[3-9][0-9]{8}" title="e.g. 017XXXXXXXX" inputMode="tel" placeholder="Mobile number (01XXXXXXXXX)" className="inp"/><input name="email" type="email" placeholder="Email (optional)" className="inp"/><textarea name="address" required placeholder="Delivery address (house, road, area)" className="inp" rows={3}/>
<div className="grid gap-4 sm:grid-cols-3"><input name="area" required placeholder="Area" className="inp"/><input name="district" required placeholder="District" className="inp" onChange={e=>setZone(/^dhaka$/i.test(e.target.value.trim())?"dhaka":"outside")}/><input name="postal" placeholder="Postal code" className="inp"/></div>
<p className="text-sm text-ink/60">Delivery zone: {zone==="dhaka"?`Inside Dhaka (${DELIVERY.labels.dhaka})`:`Outside Dhaka (${DELIVERY.labels.outside})`}</p>
<fieldset className="space-y-2"><legend className="mb-2 font-medium">Payment</legend>{["Cash on Delivery","bKash","Nagad","Card"].map(m=><label key={m} className="flex items-center gap-3 rounded-xl border border-ink/15 bg-white p-4 text-sm"><input type="radio" checked={pay===m} onChange={()=>setPay(m)}/>{m}</label>)}</fieldset></div>
<aside className="h-fit rounded-3xl bg-white p-6 text-sm"><h2 className="mb-3 font-medium">Order summary</h2>{lines.map((l,i)=><div key={i} className="flex justify-between py-1"><span>{l.name} × {l.qty}</span><span>{fmt(l.price*l.qty)}</span></div>)}<hr className="my-3"/><div className="flex justify-between"><span>Subtotal</span><span>{fmt(subtotal)}</span></div><div className="flex justify-between"><span>Delivery</span><span>{fmt(delivery(zone))}</span></div><div className="mt-2 flex justify-between text-base font-medium"><span>Total</span><span>{fmt(total)}</span></div><button disabled={!lines.length} className="btn mt-5 w-full disabled:opacity-40">Place order</button></aside></form>}
